[package]
name = "vecm"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.18"
binverse = { version = "0.6.2", optional = true }
serde = { version = "1.0.196", features = ["derive"], optional = true }

[dev-dependencies]
rand = "0.8.5"
